-- Elibless Managers property system schema

create extension if not exists "pgcrypto";

create table if not exists public.admin_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'admin' check (role in ('admin', 'manager')),
  created_at timestamptz not null default now()
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text,
  price numeric(14,2) not null default 0,
  currency text not null default 'NGN',
  property_type text not null,
  listing_type text not null check (listing_type in ('sale', 'rent')),
  location text,
  address text,
  city text,
  state text,
  bedrooms integer not null default 0,
  bathrooms integer not null default 0,
  toilets integer not null default 0,
  property_size integer not null default 0,
  year_built integer,
  status text not null default 'available' check (status in ('available', 'pending', 'sold', 'leased', 'rented', 'unavailable')),
  featured boolean not null default false,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.property_images (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  image_url text not null,
  display_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.property_amenities (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  amenity text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete set null,
  name text not null,
  email text not null,
  phone text not null,
  message text not null,
  status text not null default 'New' check (status in ('New', 'Contacted', 'Closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_properties_slug on public.properties(slug);
create index if not exists idx_properties_listing_type on public.properties(listing_type);
create index if not exists idx_properties_property_type on public.properties(property_type);
create index if not exists idx_properties_location on public.properties(location);
create index if not exists idx_properties_status on public.properties(status);
create index if not exists idx_properties_published on public.properties(published);
create index if not exists idx_properties_featured on public.properties(featured);
create index if not exists idx_property_images_property_id on public.property_images(property_id);
create index if not exists idx_property_amenities_property_id on public.property_amenities(property_id);
create index if not exists idx_enquiries_property_id on public.enquiries(property_id);
create index if not exists idx_enquiries_status on public.enquiries(status);

create or replace function public.update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger properties_set_updated_at
before update on public.properties
for each row
execute function public.update_updated_at();

create trigger enquiries_set_updated_at
before update on public.enquiries
for each row
execute function public.update_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_profiles ap
    where ap.id = auth.uid()
      and ap.role = 'admin'
  );
$$;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_admin() to anon;

alter table public.admin_profiles enable row level security;
alter table public.properties enable row level security;
alter table public.property_images enable row level security;
alter table public.property_amenities enable row level security;
alter table public.enquiries enable row level security;

create policy "Users can view their own admin profile"
on public.admin_profiles
for select
using (id = auth.uid());

create policy "Admins can manage their own admin profile"
on public.admin_profiles
for all
using (id = auth.uid())
with check (id = auth.uid() and role = 'admin');

create policy "Public can read published properties"
on public.properties
for select
using (published = true and status in ('available', 'pending'));

create policy "Admins can manage properties"
on public.properties
for all
using (public.is_admin())
with check (public.is_admin());

create policy "Public can read property images for published listings"
on public.property_images
for select
using (
  exists (
    select 1
    from public.properties p
    where p.id = property_id
      and p.published = true
      and p.status in ('available', 'pending')
  )
);

create policy "Admins can manage property images"
on public.property_images
for all
using (public.is_admin())
with check (public.is_admin());

create policy "Public can read property amenities for published listings"
on public.property_amenities
for select
using (
  exists (
    select 1
    from public.properties p
    where p.id = property_id
      and p.published = true
      and p.status in ('available', 'pending')
  )
);

create policy "Admins can manage property amenities"
on public.property_amenities
for all
using (public.is_admin())
with check (public.is_admin());

create policy "Anyone can submit property enquiries"
on public.enquiries
for insert
with check (true);

create policy "Public users can view property enquiries"
on public.enquiries
for select
using (public.is_admin());

create policy "Admins can view and update enquiries"
on public.enquiries
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage storage bucket" on storage.objects;
drop policy if exists "Public can view property images in storage" on storage.objects;

create policy "Admins can upload property images"
on storage.objects
for insert
with check (
  bucket_id = 'property-images'
  and public.is_admin()
  and (storage.foldername(name))[1] = 'properties'
);

create policy "Admins can update property images"
on storage.objects
for update
using (
  bucket_id = 'property-images'
  and public.is_admin()
)
with check (
  bucket_id = 'property-images'
  and public.is_admin()
  and (storage.foldername(name))[1] = 'properties'
);

create policy "Admins can delete property images"
on storage.objects
for delete
using (
  bucket_id = 'property-images'
  and public.is_admin()
);

create policy "Public can view property images in storage"
on storage.objects
for select
using (
  bucket_id = 'property-images'
  and (storage.foldername(name))[1] = 'properties'
);

select storage.create_bucket('property-images', true, 'public');
